### ISSUE TITLE
[Vite incompatible] Failed to resolve entry for package "kalend-layout"

### ISSUE THREAD

**Issue by williamchenghu** [nibdo/kalend#121]
**Describe the bug**
When the project was built/scaffolded with [Vite](https://vitejs.dev/), `npm run dev` will throw error about dependency _kalend-layout_  entry

**To Reproduce**
1. install _kalend_ with `npm i kalend`
2. run dev env. locally with `npm run dev`
3. See error
<img width="605" alt="Screenshot 2022-02-11 at 10 30 10" src="https://user-images.githubusercontent.com/4009417/153575040-45c8a7c8-74ea-49c5-ac83-ab06b5f0da2d.png">

~~**Interim workaround**~~
~~delete the main entry line (` "main": "dist/main.js",`) under dependency _kalend-layout_'s _package.json_ (`node_modules/kalend-layout/package.json`)~~ [**UPDATE**]: delete the entry does run `npm run dev` successfully, but _kalend-layout_ won't be loaded thus not shown on actual project.
<img width="504" alt="Screenshot 2022-02-11 at 12 00 39" src="https://user-images.githubusercontent.com/4009417/153575714-c99d5193-9f17-4082-a0f4-41bd27d198f5.png">

**Expected behavior**
Vite support with correct entry configured at build

**Full Error Message**
<details>
  <summary>full console output</summary>
    
  ```console
    npm run dev
    kalend-test@0.0.0 dev
    
    vite
    Pre-bundling dependencies:
    react
    react-dom
    @mui/material/useMediaQuery
    @mui/material/styles
    @mui/material/CssBaseline
    (...and 30 more)
    (this will be run only when your dependencies or config have changed)
    ✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "kalend-layout". The package may have incorrect 
    main/module/exports specified in its package.json: Failed to resolve entry for package "kalend-layout". The package may have 
    incorrect main/module/exports specified in its package.json.
    
    node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29511:10:
    29511 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵           ^
    
    at packageEntryFailure (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29511:11)
    at resolvePackageEntry (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29507:9)
    at tryNodeResolve (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29323:20)
    at Context.resolveId (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29140:28)
    at Object.resolveId (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:38242:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:70928:27
    at async /Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:55556:34
    at async callback (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:919:28)
    at async handleRequest (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:699:30)
    
    This error came from the "onResolve" callback registered here:
    
    node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:55535:18:
    55535 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind }) => {
          ╵                   ~~~~~~~~~
    
    at setup (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:55535:19)
    at handlePlugins (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:841:23)
    at Object.buildOrServe (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1135:7)
    at /Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:2059:17
    at new Promise (<anonymous>)
    at Object.build (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:2058:14)
    at Object.build (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1912:51)
    at optimizeDeps (/Users/william/opt/gitlocal/kalend-test/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:55790:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
    The plugin "vite:dep-pre-bundle" was triggered by this import
    
    node_modules/kalend/dist/main.js:5:34:
    5 │ var $cw6c3$kalendlayout = require("kalend-layout");
      ╵                                   ~~~~~~~~~~~~~~~
    
    error when starting dev server:
    Error: Build failed with 1 error:
    node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29511:10: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry 
    for package "kalend-layout". The package may have incorrect main/module/exports specified in its package.json: Failed to 
    resolve entry for package "kalend-layout". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1601:15)
    at /Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1247:28
    at runOnEndCallbacks (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1032:63)
    at buildResponseToResult (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1245:7)
    at /Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:1354:14
    at /Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:664:9
    at handleIncomingPacket (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:761:9)
    at Socket.readFromStdout (/Users/william/opt/gitlocal/kalend-test/node_modules/esbuild/lib/main.js:631:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
  ```
</details>

**Desktop (please complete the following information):**
 - OS: macOS 12.1
 - Browser:  Chrome version 98.0.4758.80 (Official Build) (arm64)
 - Version 
    - vite: v2.8.0

**Additional context**
N/A

**Comment by williamchenghu** [comment]
Hi @nibdo, awesome speedy fix ✅ . 0.9.5 truly does the job! Thanks for the help!
